version: "3.9"

services:
  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-5
    container_name: graphite
    ports:
      - "8080:80"         # Graphite Web UI/API
      - "2003:2003"       # Carbon plaintext input (TCP) - optional
      - "8125:8125/udp"   # StatsD input (UDP) for dumphfdl metrics
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - graphite
      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DATABASE_WAL=true
      - GF_DATABASE_SQLITE_BUSY_TIMEOUT=10000
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"       # Loki HTTP API
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    depends_on:
      - loki
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - /tmp:/logs:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
    restart: unless-stopped
