server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: dumphfdl
    static_configs:
      - targets: [localhost]
        labels:
          job: dumphfdl
          __path__: /logs/hfdl_*.jsonl   # mapped from /tmp/hfdl.jsonl in docker-compose

    pipeline_stages:
      # 1) parse your JSON (everything under "hfdl")
      - json:
          expressions:
            app: hfdl.app.name
            ver: hfdl.app.ver
            station: hfdl.station
            tsecs: hfdl.t.sec
            tusec: hfdl.t.usec
            freq: hfdl.freq
            bit_rate: hfdl.bit_rate
            sig_db: hfdl.sig_level
            noise_db: hfdl.noise_level
            skew_hz: hfdl.freq_skew
            slot: hfdl.slot

            # LPDU basics
            lpdu_type_id: hfdl.lpdu.type.id
            lpdu_type: hfdl.lpdu.type.name
            src_type: hfdl.lpdu.src.type
            src_id: hfdl.lpdu.src.id
            dst_type: hfdl.lpdu.dst.type
            dst_id: hfdl.lpdu.dst.id
            dst_name: hfdl.lpdu.dst.name
            icao: hfdl.lpdu.ac_info.icao

            # HFNPDU / ACARS bits (present in many messages)
            hfnpdu_type_id: hfdl.lpdu.hfnpdu.type.id
            hfnpdu_type: hfdl.lpdu.hfnpdu.type.name
            flight_id: hfdl.lpdu.hfnpdu.flight_id

            # position if present
            pos_lat: hfdl.lpdu.hfnpdu.pos.lat
            pos_lon: hfdl.lpdu.hfnpdu.pos.lon

            # ACARS envelope (when present)
            acars_label: hfdl.lpdu.hfnpdu.acars.label
            acars_flight: hfdl.lpdu.hfnpdu.acars.flight
            acars_reg: hfdl.lpdu.hfnpdu.acars.reg
            acars_msg: hfdl.lpdu.hfnpdu.acars.msg_text

      # 2) normalize dst_name for use as a label (spaces/commas -> underscores)
      - replace:
          source: dst_name
          expression: '[^A-Za-z0-9_.-]'
          replace: '_'

      # 3) promote selected fields to Loki labels (fast filters in Explore)
      - labels:
          station:
          freq:
          bit_rate:
          slot:
          lpdu_type:
          dst_type:
          dst_name:     # e.g., Albrook,_Panama
          icao:
          flight_id:
          acars_label:
          acars_flight:

      # 4) use device time (seconds) rather than ingestion time
      - timestamp:
          source: tsecs
          format: Unix
